spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        tags:
          -dev


management:
  endpoints:
    web:
      exposure:
        include: health,refresh, info

global:
  message: "Hello from shared config!"


