server:
  port: 8082
  servlet:
    context-path: /service1-dev

app:
  name: "Service 1"
  version: "1.0.3:latest"
  developer: "rbd@email.com"
  feature-flags:
    enableNewUI: true
    enableLogging: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service1_dev
    username: dev_user
    password: dev_pass

logging:
  level:
    root: INFO
    com.service1: DEBUG



